### ISSUE TITLE
grep -q Darwin?

### ISSUE THREAD

**Issue by karsens** [jorinvo/me#8]
I tried your script to find short handles, but this command didn't work. Don't know what it's suposed to do, but I deleted it and then the script started working 👍

**Comment by jorinvo** [comment]
hi @karsens, this part checking if you are running MacOS, and if so, it makes sure you have the `shuf` command installed.

Which OS did you use to  run the script?

**Comment by karsens** [comment]
MacOS and when I type 'uname' it outputs Darwin.

**Comment by karsens** [comment]
"grep -q Darwin" just keeps loading forever

**Comment by jorinvo** [comment]
yes, `Darwin` means that you have a Mac.
`grep` on its own doesn't do anything. It is stuck because it is waiting for some input.
If you do `uname | grep Darwin`, it checks if your computer is a Mac. The `-q` flag just keeps grep quiet because for the `if` statement we only care about the exit code, not the output, of the command.
You can remove that section from the script without worries as long as you have the `shuf` command installed.

**Comment by karsens** [comment]
Allright. Yeah, somehow it didn't output anything if I had that part of code. So I commented it out (and had shuf installed) and then it worked 👍
